/**
 * ItineraryDisplay.jsx
 *
 * @description  Renders the complete AI-generated travel itinerary with
 *               interactive maps, crowd analysis, weather data, budget
 *               breakdown, and Plan B swap functionality. Supports PDF
 *               export and WhatsApp sharing.
 *
 *               v2: Replaced Daily Dose with Nearby Highlights,
 *                   premium PDF/WhatsApp formatting (no cartoon emojis),
 *                   mobile-first responsive layout.
 */

import React, { useState } from 'react';
import MapComponent from './MapComponent';
import jsPDF from 'jspdf';
import CrowdAnalyzer from './CrowdAnalyzer';
import SurvivalGrid from './SurvivalGrid';
import BookingHub from './BookingHub';
import {
  Download, RefreshCw, Zap, Wind,
  Navigation, Clock, CheckCircle2,
  Share2, Wallet, Users, TrendingUp, Info,
  Trees, Clapperboard, ShoppingBag, Eye, MapPin, Copy, Send, Twitter, Lightbulb,
  Backpack, X, Shirt, Heart, FileText, Loader2, Check
} from 'lucide-react';

export default function ItineraryDisplay({ itinerary, onEdit, onSwitchPlan }) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [showBooking, setShowBooking] = useState(false);
  const [showShareMenu, setShowShareMenu] = useState(false);
  const [showPackingList, setShowPackingList] = useState(false);
  const [packingData, setPackingData] = useState(null);
  const [packingLoading, setPackingLoading] = useState(false);
  const [checkedItems, setCheckedItems] = useState({});

  const PACKING_API = window.location.hostname === 'localhost'
    ? 'http://localhost:5000/api/packing-list'
    : 'https://sanchaara-ai.onrender.com/api/packing-list';

  const packingIcons = {
    shirt: <Shirt className="w-4 h-4" />,
    heart: <Heart className="w-4 h-4" />,
    zap: <Zap className="w-4 h-4" />,
    file: <FileText className="w-4 h-4" />,
    backpack: <Backpack className="w-4 h-4" />,
  };

  const fetchPackingList = async () => {
    if (packingData) { setShowPackingList(true); return; }
    setShowPackingList(true);
    setPackingLoading(true);
    try {
      const activities = itinerary.days.flatMap(d => d.places.map(p => p.name)).join(', ');
      const weather = itinerary.days[0]?.weather?.condition || itinerary.seasonalNote || '';
      const res = await fetch(PACKING_API, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          destination: itinerary.days[0]?.cityLocation,
          days: itinerary.days.length,
          weather,
          activities,
          travelers: itinerary.budgetAnalysis?.perPerson ? 'multiple' : '1'
        }),
      });
      const data = await res.json();
      if (data.error) throw new Error(data.error);
      setPackingData(data);
    } catch (err) {
      console.error('Packing list error:', err);
      alert('Could not generate packing list. Please try again.');
      setShowPackingList(false);
    } finally {
      setPackingLoading(false);
    }
  };

  const toggleCheck = (catIdx, itemIdx) => {
    const key = `${catIdx}-${itemIdx}`;
    setCheckedItems(prev => ({ ...prev, [key]: !prev[key] }));
  };

  if (!itinerary || !itinerary.days || !itinerary.initialLogistics) return null;

  // --- HELPER: SAFE RENDERER (Prevents Object-as-child crash) ---
  const safeRender = (data) => {
    if (!data) return "";
    if (typeof data === 'string' || typeof data === 'number') return data;
    if (typeof data === 'object') return data.name || data.value || data.text || JSON.stringify(data);
    return "";
  };

  // --- SHARE TEXT BUILDER (WhatsApp markdown) ---
  const buildShareText = () => {
    const line = '─'.repeat(28);
    let text = `*SANCHAARA AI — TRIP DOSSIER*\n`;
    text += `${line}\n\n`;
    text += `*Route*: ${itinerary.initialLogistics.from} > ${itinerary.days[0].cityLocation}\n`;
    text += `*Total Investment*: ${renderBudget(itinerary.estimatedTotalCost)}\n`;
    text += `*Per Head*: ${itinerary.budgetAnalysis?.perPerson || 'N/A'}\n\n`;
    text += `${line}\n`;

    itinerary.days.forEach(day => {
      text += `\n*DAY ${day.dayNumber} — ${day.cityLocation}*\n`;
      text += `_${day.date || ''}_\n\n`;
      day.places.forEach(p => {
        text += `  • *${p.name}*\n`;
        text += `    Arrive: ${p.time} | Traffic: ${p.trafficStatus || 'Normal'}\n`;
      });

      if (day.nearbyHighlights) {
        const h = day.nearbyHighlights;
        text += `\n  _Nearby_:\n`;
        if (h.parks) text += `    Park — ${h.parks}\n`;
        if (h.theatres) text += `    Theatre — ${h.theatres}\n`;
        if (h.shopping) text += `    Shopping — ${h.shopping}\n`;
        if (h.viewpoint) text += `    Viewpoint — ${h.viewpoint}\n`;
      }
      text += `\n${line}\n`;
    });

    text += `\nGenerated by Sanchaara AI`;
    return text;
  };

  // --- PLAIN TEXT BUILDER (no markdown symbols) ---
  const buildPlainText = () => {
    return buildShareText().replace(/\*/g, '').replace(/_/g, '');
  };

  const shareToWhatsApp = () => {
    window.open(`https://wa.me/?text=${encodeURIComponent(buildShareText())}`, '_blank');
    setShowShareMenu(false);
  };

  const shareToTelegram = () => {
    window.open(`https://t.me/share/url?url=${encodeURIComponent('Sanchaara AI')}&text=${encodeURIComponent(buildPlainText())}`, '_blank');
    setShowShareMenu(false);
  };

  const shareToTwitter = () => {
    const brief = `Check out my trip to ${itinerary.days[0].cityLocation} planned by Sanchaara AI! ${renderBudget(itinerary.estimatedTotalCost)} for ${itinerary.days.length} days.`;
    window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(brief)}`, '_blank');
    setShowShareMenu(false);
  };

  const copyToClipboard = async () => {
    try {
      await navigator.clipboard.writeText(buildPlainText());
      alert('Trip plan copied! Paste it anywhere — Instagram, notes, or messages.');
    } catch { alert('Could not copy. Please try again.'); }
    setShowShareMenu(false);
  };

  // --- PROFESSIONAL VECTOR PDF GENERATOR (No emojis) ---
  const exportPDF = () => {
    setIsGenerating(true);
    const doc = new jsPDF();
    let yPos = 20;

    const checkPage = (height) => {
      if (yPos + height > 275) { doc.addPage(); yPos = 20; return true; }
      return false;
    };

    const drawLine = (y) => {
      doc.setDrawColor(200, 200, 200);
      doc.setLineWidth(0.2);
      doc.line(20, y, 190, y);
    };

    // ── HEADER ──
    doc.setFillColor(15, 23, 42);
    doc.rect(0, 0, 210, 44, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont("helvetica", "bold");
    doc.text('SANCHAARA AI', 20, 18);
    doc.setFontSize(9);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(180, 200, 230);
    doc.text('Trip Dossier', 20, 25);
    doc.setFontSize(10);
    doc.setTextColor(255, 255, 255);
    doc.text(`${itinerary.initialLogistics.from}  >  ${itinerary.days[0].cityLocation}`, 20, 34);
    doc.setFontSize(9);
    doc.setTextColor(160, 220, 180);
    doc.text(`Total: ${renderBudget(itinerary.estimatedTotalCost)}  |  Per Head: ${safeRender(itinerary.budgetAnalysis?.perPerson) || 'N/A'}`, 20, 40);

    yPos = 54;

    // ── ITINERARY DAYS ──
    itinerary.days.forEach((day, dIdx) => {
      checkPage(50);

      // Day header bar
      doc.setFillColor(240, 245, 255);
      doc.roundedRect(20, yPos, 170, 12, 2, 2, 'F');
      doc.setTextColor(30, 64, 175);
      doc.setFontSize(10);
      doc.setFont("helvetica", "bold");
      doc.text(`DAY ${dIdx + 1}  —  ${day.cityLocation}`, 25, yPos + 8);
      doc.setFontSize(8);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(120, 120, 140);
      doc.text(day.date || '', 170, yPos + 8);
      yPos += 18;

      // Places
      day.places.forEach((place) => {
        const desc = doc.splitTextToSize(place.description || '', 130);
        checkPage(28 + (desc.length * 4));

        doc.setTextColor(30, 30, 30);
        doc.setFont("helvetica", "bold");
        doc.setFontSize(10);
        doc.text(place.name, 25, yPos);

        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(80, 80, 80);
        doc.text(`Arrive: ${place.time}  |  Traffic: ${place.trafficStatus || 'Normal'}  |  Dist: ${place.distanceFromPrevious || 'Local'}`, 25, yPos + 5);

        if (desc.length > 0 && desc[0]) {
          doc.setFontSize(8);
          doc.setTextColor(100, 100, 100);
          doc.text(desc, 25, yPos + 10);
        }
        yPos += (desc.length * 4) + 16;
      });

      // Nearby Highlights
      if (day.nearbyHighlights) {
        checkPage(22);
        doc.setFontSize(8);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(60, 100, 60);
        doc.text('NEARBY HIGHLIGHTS', 25, yPos);
        yPos += 5;
        doc.setFont("helvetica", "normal");
        doc.setTextColor(80, 80, 80);
        const nh = day.nearbyHighlights;
        const highlights = [
          nh.parks && `Park: ${nh.parks}`,
          nh.theatres && `Theatre: ${nh.theatres}`,
          nh.shopping && `Shopping: ${nh.shopping}`,
          nh.viewpoint && `Viewpoint: ${nh.viewpoint}`,
        ].filter(Boolean);
        highlights.forEach(h => {
          doc.text(h, 28, yPos);
          yPos += 4;
        });
        yPos += 4;
      }

      drawLine(yPos);
      yPos += 8;
    });

    // ── BUDGET BREAKDOWN ──
    if (itinerary.budgetAnalysis?.breakdown) {
      checkPage(40);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 30, 30);
      doc.text('BUDGET BREAKDOWN', 20, yPos);
      yPos += 8;

      Object.entries(itinerary.budgetAnalysis.breakdown)
        .filter(([key]) => !key.toLowerCase().includes('financial') && !key.toLowerCase().includes('warning'))
        .forEach(([key, val]) => {
          checkPage(8);
          doc.setFontSize(9);
          doc.setFont("helvetica", "normal");
          doc.setTextColor(60, 60, 60);
          doc.text(key.charAt(0).toUpperCase() + key.slice(1), 25, yPos);
          doc.setFont("helvetica", "bold");
          doc.setTextColor(30, 30, 30);
          doc.text(safeRender(val), 140, yPos);
          yPos += 6;
        });
    }

    // ── FOOTER ──
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setFontSize(7);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(160, 160, 160);
      doc.text(`Sanchaara AI  |  Page ${i} of ${pageCount}  |  Generated ${new Date().toLocaleDateString()}`, 20, 290);
    }

    doc.save(`Sanchaara-Dossier-${itinerary.days[0].cityLocation}.pdf`);
    setIsGenerating(false);
  };

  const getTrafficDetails = (status) => {
    const s = status?.toLowerCase() || '';
    if (s.includes('high')) return { color: 'text-red-400', bg: 'bg-red-500/20', label: 'HEAVY' };
    if (s.includes('moderate')) return { color: 'text-yellow-400', bg: 'bg-yellow-500/20', label: 'MODERATE' };
    return { color: 'text-emerald-400', bg: 'bg-emerald-500/20', label: 'CLEAR' };
  };

  const renderBudget = (budget) => {
    if (typeof budget === 'object' && budget !== null) {
      return `₹${budget.value || budget.total || 'Calculated'}`;
    }
    return budget;
  };

  // --- NEARBY HIGHLIGHTS CONFIG ---
  const highlightCategories = [
    { key: 'parks', icon: <Trees className="w-4 h-4 sm:w-5 sm:h-5" />, label: 'Park', color: 'text-emerald-400', hoverBg: 'hover:bg-emerald-500/20' },
    { key: 'theatres', icon: <Clapperboard className="w-4 h-4 sm:w-5 sm:h-5" />, label: 'Theatre', color: 'text-purple-400', hoverBg: 'hover:bg-purple-500/20' },
    { key: 'shopping', icon: <ShoppingBag className="w-4 h-4 sm:w-5 sm:h-5" />, label: 'Shopping', color: 'text-amber-400', hoverBg: 'hover:bg-amber-500/20' },
    { key: 'viewpoint', icon: <Eye className="w-4 h-4 sm:w-5 sm:h-5" />, label: 'Viewpoint', color: 'text-cyan-400', hoverBg: 'hover:bg-cyan-500/20' },
  ];

  return (
    <div className="min-h-screen w-full p-2 sm:p-4 md:p-8 animate-fade-in relative z-10 text-white font-sans selection:bg-emerald-500/30">

      {/* NAVIGATION (Mobile-first) */}
      <nav className="max-w-7xl mx-auto flex flex-col sm:flex-row justify-between items-center mb-6 sm:mb-10 gap-4 sm:gap-6 bg-white/5 backdrop-blur-2xl p-3 sm:p-4 md:p-6 rounded-2xl sm:rounded-[2rem] md:rounded-[2.5rem] border border-white/10 shadow-2xl relative z-50">
        <div className="text-center sm:text-left">
          <h2 className="text-2xl sm:text-3xl md:text-4xl font-black tracking-tighter italic">SANCHAARA <span className="text-blue-400 font-normal">AI</span></h2>
          <p className="text-[8px] sm:text-[9px] font-bold uppercase tracking-[0.3em] sm:tracking-[0.4em] text-white/40">Intelligent Journey Partner</p>
        </div>

        <div className="flex items-center gap-2 sm:gap-3">
          <div className="relative">
            <button onClick={() => setShowShareMenu(!showShareMenu)} className="group/btn relative overflow-hidden flex items-center gap-1.5 sm:gap-2 bg-gradient-to-r from-blue-600/10 via-purple-600/10 to-blue-600/10 hover:from-blue-600/25 hover:via-purple-600/25 hover:to-blue-600/25 text-white/70 hover:text-white border border-white/10 hover:border-blue-400/30 px-3 py-2 sm:px-4 sm:py-2.5 md:px-5 md:py-3 rounded-xl sm:rounded-2xl font-black text-[8px] sm:text-[9px] md:text-[10px] uppercase tracking-wider sm:tracking-widest transition-all duration-500 active:scale-[0.97] shadow-lg hover:shadow-blue-500/20">
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent translate-x-[-100%] group-hover/btn:translate-x-[100%] transition-transform duration-700"></div>
              <Share2 className="relative w-3.5 h-3.5 sm:w-4 sm:h-4" /> <span className="relative">Share</span>
            </button>
            {showShareMenu && (
              <>
                <div className="fixed inset-0 z-[60]" onClick={() => setShowShareMenu(false)}></div>
                <div className="absolute right-0 top-full mt-2 z-[70] bg-[#0c1425] border border-white/10 rounded-xl sm:rounded-2xl shadow-[0_8px_40px_rgba(0,0,0,0.8)] p-1.5 min-w-[190px]">
                  <button onClick={shareToWhatsApp} className="w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl hover:bg-white/5 transition-all text-left group">
                    <div className="w-8 h-8 rounded-lg bg-[#25D366]/15 flex items-center justify-center shrink-0"><Send className="w-3.5 h-3.5 text-[#25D366]" /></div>
                    <span className="text-[10px] font-black text-white/60 uppercase tracking-wider group-hover:text-white transition-colors">WhatsApp</span>
                  </button>
                  <button onClick={shareToTelegram} className="w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl hover:bg-white/5 transition-all text-left group">
                    <div className="w-8 h-8 rounded-lg bg-[#0088cc]/15 flex items-center justify-center shrink-0"><Send className="w-3.5 h-3.5 text-[#0088cc]" /></div>
                    <span className="text-[10px] font-black text-white/60 uppercase tracking-wider group-hover:text-white transition-colors">Telegram</span>
                  </button>
                  <button onClick={shareToTwitter} className="w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl hover:bg-white/5 transition-all text-left group">
                    <div className="w-8 h-8 rounded-lg bg-white/5 flex items-center justify-center shrink-0"><Twitter className="w-3.5 h-3.5 text-white/70" /></div>
                    <span className="text-[10px] font-black text-white/60 uppercase tracking-wider group-hover:text-white transition-colors">X / Twitter</span>
                  </button>
                  <div className="h-px bg-white/5 my-1 mx-2"></div>
                  <button onClick={copyToClipboard} className="w-full flex items-center gap-3 px-3.5 py-2.5 rounded-xl hover:bg-white/5 transition-all text-left group">
                    <div className="w-8 h-8 rounded-lg bg-blue-500/10 flex items-center justify-center shrink-0"><Copy className="w-3.5 h-3.5 text-blue-400" /></div>
                    <span className="text-[10px] font-black text-white/60 uppercase tracking-wider group-hover:text-white transition-colors">Copy Plan</span>
                  </button>
                </div>
              </>
            )}
          </div>
          <button onClick={onEdit} className="group/btn relative overflow-hidden p-2 sm:p-3 bg-gradient-to-r from-blue-600/10 via-purple-600/10 to-blue-600/10 hover:from-blue-600/25 hover:via-purple-600/25 hover:to-blue-600/25 rounded-xl sm:rounded-2xl transition-all duration-500 border border-white/10 hover:border-blue-400/30 active:scale-[0.97] shadow-lg hover:shadow-blue-500/20">
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent translate-x-[-100%] group-hover/btn:translate-x-[100%] transition-transform duration-700"></div>
            <RefreshCw className="relative w-4 h-4 sm:w-5 sm:h-5 text-white/60 group-hover/btn:text-white transition-colors" />
          </button>
          <button onClick={fetchPackingList} className="group/btn relative overflow-hidden flex items-center gap-1.5 sm:gap-2 bg-gradient-to-r from-blue-600/10 via-purple-600/10 to-blue-600/10 hover:from-blue-600/25 hover:via-purple-600/25 hover:to-blue-600/25 text-white/70 hover:text-white border border-white/10 hover:border-blue-400/30 px-3 py-2 sm:px-4 sm:py-2.5 md:px-5 md:py-3 rounded-xl sm:rounded-2xl font-black text-[8px] sm:text-[9px] md:text-[10px] uppercase tracking-wider sm:tracking-widest transition-all duration-500 active:scale-[0.97] shadow-lg hover:shadow-blue-500/20">
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent translate-x-[-100%] group-hover/btn:translate-x-[100%] transition-transform duration-700"></div>
            <Backpack className="relative w-3.5 h-3.5 sm:w-4 sm:h-4" /> <span className="relative">Pack List</span>
          </button>
          <button onClick={exportPDF} disabled={isGenerating} className="group/btn relative overflow-hidden flex items-center gap-1.5 sm:gap-2 bg-gradient-to-r from-blue-600/10 via-purple-600/10 to-blue-600/10 hover:from-blue-600/25 hover:via-purple-600/25 hover:to-blue-600/25 text-white/70 hover:text-white border border-white/10 hover:border-blue-400/30 px-3 py-2 sm:px-4 sm:py-2.5 md:px-6 md:py-3 rounded-xl sm:rounded-2xl font-black text-[8px] sm:text-[9px] md:text-[10px] uppercase tracking-wider sm:tracking-widest transition-all duration-500 active:scale-[0.97] shadow-lg hover:shadow-blue-500/20 disabled:opacity-50 disabled:cursor-not-allowed">
            <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent translate-x-[-100%] group-hover/btn:translate-x-[100%] transition-transform duration-700"></div>
            <Download className="relative w-3.5 h-3.5 sm:w-4 sm:h-4" /> <span className="relative">{isGenerating ? 'Generating...' : 'Export PDF'}</span>
          </button>
        </div>
      </nav>

      {/* SEASONAL INSIGHT + LOCAL PULSE */}
      <div className="max-w-7xl mx-auto space-y-4 sm:space-y-6 mb-8 sm:mb-16">
        {itinerary.seasonalNote && (
          <div className="bg-gradient-to-r from-amber-500/20 to-orange-600/20 backdrop-blur-xl border border-amber-500/30 p-4 sm:p-6 md:p-8 rounded-2xl sm:rounded-[2rem] md:rounded-[2.5rem] shadow-2xl flex flex-col sm:flex-row items-center gap-4 sm:gap-6 md:gap-8 group">
            <div className="bg-amber-400 text-black w-12 h-12 sm:w-16 sm:h-16 md:w-20 md:h-20 rounded-2xl sm:rounded-3xl flex items-center justify-center shadow-xl">
              <Lightbulb className="w-6 h-6 sm:w-8 sm:h-8 md:w-10 md:h-10" />
            </div>
            <div className="text-center sm:text-left">
              <span className="bg-amber-400/20 text-amber-400 text-[9px] sm:text-[10px] font-black uppercase tracking-[0.2em] sm:tracking-[0.3em] px-3 py-1 rounded-full border border-amber-400/20">Seasonal Intelligence</span>
              <p className="text-amber-50/80 text-sm sm:text-base md:text-lg font-medium italic mt-2 sm:mt-3 leading-relaxed">"{itinerary.seasonalNote}"</p>
            </div>
          </div>
        )}

        {itinerary.localPulse && itinerary.localPulse.length > 0 && (
          <div className="bg-gradient-to-r from-blue-600/10 to-purple-600/10 backdrop-blur-xl border border-blue-500/20 p-4 sm:p-6 md:p-8 rounded-2xl sm:rounded-[2rem] md:rounded-[2.5rem] shadow-xl">
            <h6 className="text-blue-400 text-[9px] sm:text-[10px] font-black uppercase tracking-[0.2em] sm:tracking-[0.3em] mb-4 sm:mb-6 flex items-center gap-2">
              <TrendingUp className="w-4 h-4" /> Local Pulse
            </h6>
            <div className="flex flex-wrap gap-3 sm:gap-4 md:gap-5">
              {itinerary.localPulse.map((event, i) => (
                <div key={i} className="flex items-center gap-2.5 sm:gap-3 bg-white/5 border border-white/10 px-4 py-2 sm:px-5 sm:py-3 rounded-xl sm:rounded-2xl hover:bg-white/10 hover:border-white/20 transition-all cursor-default">
                  <div className="w-1.5 h-1.5 sm:w-2 sm:h-2 rounded-full bg-blue-400"></div>
                  <span className="text-blue-50/90 font-bold text-[10px] sm:text-xs md:text-sm uppercase tracking-wide">
                    {safeRender(event)}
                  </span>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      <main className="max-w-7xl mx-auto space-y-12 sm:space-y-16 md:space-y-20">

        {/* DEPARTURE SECTION */}
        <section className="bg-white/5 backdrop-blur-xl rounded-2xl sm:rounded-[2rem] md:rounded-[3rem] border border-white/10 shadow-2xl overflow-hidden grid grid-cols-1 lg:grid-cols-3">
          <div className="p-5 sm:p-8 md:p-10 lg:col-span-1 flex flex-col justify-center border-b lg:border-b-0 lg:border-r border-white/5">
            <span className="text-blue-400 font-black text-[9px] sm:text-[10px] tracking-widest uppercase mb-3 sm:mb-4 flex items-center gap-2"><Navigation className="w-3 h-3" /> Initial Transit</span>
            <h3 className="text-2xl sm:text-3xl md:text-4xl font-black mb-5 sm:mb-8 leading-tight tracking-tighter text-center lg:text-left">
              {itinerary.initialLogistics.from} <br className="hidden lg:block" />
              <span className="text-white/20 text-xl sm:text-2xl font-light">—</span> {itinerary.initialLogistics.to}
            </h3>
            <div className="grid grid-cols-2 gap-3 sm:gap-4">
              <div className="bg-white/5 p-3 sm:p-4 rounded-xl sm:rounded-2xl border border-white/5 text-center">
                <p className="text-white/30 text-[8px] sm:text-[9px] font-bold uppercase mb-1">Mode</p>
                <p className="font-black text-[10px] sm:text-xs uppercase text-blue-400">{itinerary.initialLogistics.mode}</p>
              </div>
              <div className="bg-white/5 p-3 sm:p-4 rounded-xl sm:rounded-2xl border border-white/5 text-center">
                <p className="text-white/30 text-[8px] sm:text-[9px] font-bold uppercase mb-1">Dist.</p>
                <p className="font-black text-[10px] sm:text-xs text-green-400 uppercase">{itinerary.initialLogistics.distance}</p>
              </div>
            </div>

            {/* Live Travel Intel — Premium CTA inside transit hub */}
            <button
              onClick={() => setShowBooking(true)}
              className="group mt-5 sm:mt-6 w-full relative overflow-hidden bg-gradient-to-r from-blue-600/10 via-purple-600/10 to-blue-600/10 hover:from-blue-600/25 hover:via-purple-600/25 hover:to-blue-600/25 border border-white/10 hover:border-blue-400/30 px-4 sm:px-5 py-3 sm:py-4 rounded-xl sm:rounded-2xl transition-all duration-500 active:scale-[0.97] shadow-lg hover:shadow-blue-500/20"
            >
              <div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent translate-x-[-100%] group-hover:translate-x-[100%] transition-transform duration-700"></div>
              <div className="relative flex items-center justify-center gap-2 sm:gap-3">
                <span className="relative flex h-2 w-2">
                  <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-75"></span>
                  <span className="relative inline-flex rounded-full h-2 w-2 bg-emerald-400"></span>
                </span>
                <span className="text-[9px] sm:text-[10px] font-black text-white/80 uppercase tracking-[0.2em] sm:tracking-[0.3em] group-hover:text-white transition-colors">Live Travel Intel</span>
              </div>
            </button>
          </div>
          <div className="lg:col-span-2 h-[250px] sm:h-[300px] md:h-[350px]">
            {itinerary.initialLogistics.mode?.toLowerCase().includes('flight') ? (
              <div className="w-full h-full relative overflow-hidden">
                <iframe
                  title="Flight Route Map"
                  src={`https://maps.google.com/maps?q=${encodeURIComponent(itinerary.initialLogistics.to)}&z=5&output=embed`}
                  className="w-full h-full border-0 grayscale opacity-60"
                  loading="lazy"
                />
                <div className="absolute inset-0 flex flex-col items-center justify-center pointer-events-none">
                  <div className="bg-slate-950/80 backdrop-blur-md border border-white/10 rounded-xl sm:rounded-2xl px-4 sm:px-8 py-3 sm:py-5 flex items-center gap-3 sm:gap-6 shadow-2xl">
                    <div className="text-center">
                      <p className="text-[6px] sm:text-[7px] font-bold text-white/30 uppercase tracking-[0.2em] mb-1">From</p>
                      <p className="text-[10px] sm:text-xs font-black text-white">{itinerary.initialLogistics.from}</p>
                    </div>
                    <div className="text-center">
                      <Navigation className="w-5 h-5 sm:w-6 sm:h-6 text-blue-400 mx-auto" />
                      <p className="text-[8px] sm:text-[9px] font-black text-blue-400 mt-1">{itinerary.initialLogistics.distance}</p>
                      <p className="text-[6px] sm:text-[7px] text-white/20 uppercase tracking-wider">aerial</p>
                    </div>
                    <div className="text-center">
                      <p className="text-[6px] sm:text-[7px] font-bold text-white/30 uppercase tracking-[0.2em] mb-1">To</p>
                      <p className="text-[10px] sm:text-xs font-black text-white">{itinerary.initialLogistics.to}</p>
                    </div>
                  </div>
                  <a
                    href={`https://www.google.com/travel/flights?q=flights+from+${encodeURIComponent(itinerary.initialLogistics.from)}+to+${encodeURIComponent(itinerary.initialLogistics.to)}`}
                    target="_blank"
                    rel="noreferrer"
                    className="pointer-events-auto mt-2 sm:mt-3 text-[8px] sm:text-[9px] font-black text-blue-400/70 hover:text-blue-400 uppercase tracking-widest border border-blue-500/20 hover:border-blue-500/40 bg-slate-950/70 px-3 sm:px-4 py-1.5 sm:py-2 rounded-lg transition-all"
                  >
                    Search Flights on Google
                  </a>
                </div>
              </div>
            ) : (
              <MapComponent origin={itinerary.initialLogistics.from} destination={itinerary.initialLogistics.to} isFlight={false} mode={itinerary.initialLogistics.mode || ''} />
            )}
          </div>
        </section>

        {/* BOOKING MODAL */}
        {showBooking && (
          <BookingHub
            logistics={itinerary.initialLogistics}
            destination={itinerary.days?.[0]?.cityLocation || ''}
            startDate={itinerary.days?.[0]?.date || ''}
            travelers={1}
            onClose={() => setShowBooking(false)}
          />
        )}

        {/* DAILY CARDS (Mobile-first Layout) */}
        <div className="space-y-10 sm:space-y-16 md:space-y-24">
          {itinerary.days.map((day, dayIdx) => (
            <div key={dayIdx} className="bg-white/5 backdrop-blur-3xl rounded-2xl sm:rounded-[2rem] md:rounded-[3.5rem] border border-white/10 shadow-2xl overflow-hidden">

              {/* Day Header */}
              <div className="bg-gradient-to-r from-blue-600/20 to-emerald-500/10 p-4 sm:p-6 md:p-8 border-b border-white/5 flex flex-col sm:flex-row justify-between items-center gap-4 sm:gap-6">
                <div className="flex items-center gap-3 sm:gap-4 md:gap-6">
                  <div className="w-10 h-10 sm:w-12 sm:h-12 md:w-16 md:h-16 bg-blue-600 text-white rounded-xl sm:rounded-2xl md:rounded-3xl flex flex-col items-center justify-center shadow-lg shrink-0">
                    <span className="text-[7px] sm:text-[8px] md:text-[10px] font-black uppercase opacity-60">Day</span>
                    <span className="text-lg sm:text-xl md:text-3xl font-black leading-none">{dayIdx + 1}</span>
                  </div>
                  <div>
                    <p className="text-blue-400 text-[8px] sm:text-[9px] md:text-[10px] font-black uppercase tracking-[0.15em] sm:tracking-[0.2em]">{day.date}</p>
                    <h4 className="text-xl sm:text-2xl md:text-4xl font-black tracking-tighter">{day.cityLocation}</h4>
                  </div>
                </div>
                <div className="bg-white/5 px-4 py-2 sm:px-5 sm:py-3 md:px-6 md:py-4 rounded-xl sm:rounded-2xl md:rounded-3xl border border-white/10 flex items-center gap-3 sm:gap-4">
                   <span className="text-2xl sm:text-3xl md:text-4xl">{day.weather?.icon || "☀️"}</span>
                   <div className="text-right">
                     <p className="text-lg sm:text-xl md:text-2xl font-black tracking-tighter">{day.weather?.temp}</p>
                     <p className="text-[7px] sm:text-[8px] md:text-[9px] font-black uppercase text-white/40 tracking-widest">{day.weather?.condition}</p>
                   </div>
                </div>
              </div>

              <div className="flex flex-col xl:flex-row">
                {/* Main Places Column */}
                <div className="flex-[2.5] p-4 sm:p-6 md:p-14 space-y-16 sm:space-y-24 md:space-y-32 border-b xl:border-b-0 xl:border-r border-white/5">
                  {day.places?.map((place, pIdx) => {
                    const traffic = getTrafficDetails(place.trafficStatus);
                    let mapOrigin;
                    if (pIdx === 0) {
                        if (dayIdx === 0) {
                            mapOrigin = itinerary.arrivalLogistics.from;
                        } else {
                            const prevDayPlaces = itinerary.days[dayIdx - 1].places;
                            mapOrigin = prevDayPlaces[prevDayPlaces.length - 1].name;
                        }
                    } else {
                        mapOrigin = day.places[pIdx - 1].name;
                    }

                    return (
                      <div key={pIdx} className="group relative">
                        <div className="flex flex-col md:flex-row gap-4 sm:gap-6 md:gap-12">

                          {/* TIME & TRAFFIC SECTION */}
                          <div className="w-full md:w-32 lg:w-40 shrink-0 flex flex-col gap-3 sm:gap-4 items-start">
                             <div className="w-full min-w-0">
                               <div className="flex items-center gap-1.5 sm:gap-2 text-blue-400 mb-1 sm:mb-2">
                                  <Clock className="w-3 h-3 sm:w-4 sm:h-4 animate-pulse" />
                                  <span className="text-[9px] sm:text-[10px] md:text-[11px] font-black uppercase tracking-[0.15em] sm:tracking-[0.2em]">Arrival</span>
                               </div>
                               <p className="text-xl sm:text-2xl md:text-3xl font-black text-white tracking-tight leading-tight break-words">{place.time}</p>
                             </div>
                             <div className="flex flex-col gap-2 sm:gap-3 md:gap-4 items-start w-full">
                               <div className={`inline-flex items-center gap-1.5 sm:gap-2 px-2 sm:px-3 py-1 sm:py-1.5 rounded-lg sm:rounded-xl text-[8px] sm:text-[9px] font-black ${traffic.bg} ${traffic.color} border border-white/5`}>
                                 <span className="w-1 h-1 sm:w-1.5 sm:h-1.5 rounded-full bg-current"></span>
                                 {traffic.label}
                               </div>
                               <div className="bg-white/5 border border-white/10 rounded-lg sm:rounded-xl px-3 py-1.5 sm:px-4 sm:py-2">
                                  <p className="text-[7px] sm:text-[8px] font-bold text-white/30 uppercase tracking-widest mb-0.5 sm:mb-1">Route</p>
                                  <p className="text-[9px] sm:text-[10px] font-black text-green-400 whitespace-nowrap overflow-hidden text-ellipsis">
                                    {pIdx === 0 && dayIdx === 0 ? itinerary.arrivalLogistics.distance : (place.distanceFromPrevious || 'Local')}
                                  </p>
                               </div>
                             </div>
                          </div>

                          <div className="flex-1 min-w-0 pl-0 md:pl-8 lg:pl-12 border-t md:border-t-0 md:border-l border-white/5 pt-6 md:pt-0 mt-2 md:mt-0">
                            <h5 className="text-xl sm:text-2xl md:text-3xl lg:text-4xl font-black text-white mb-3 sm:mb-4 md:mb-6 tracking-tight leading-tight group-hover:text-blue-300 transition-all break-words">{place.name}</h5>

                            {/* CROWD ANALYZER */}
                            <CrowdAnalyzer analysis={place.crowdAnalysis} />

                            <p className="text-white/60 my-4 sm:my-6 md:my-8 leading-relaxed italic text-sm sm:text-base md:text-lg border-l-2 border-blue-500/30 pl-4 sm:pl-6 py-1">{place.description}</p>

                            <div className="rounded-xl sm:rounded-[2rem] md:rounded-[2.5rem] overflow-hidden border border-white/10 h-48 sm:h-64 md:h-80 transition-all shadow-2xl">
                              <MapComponent origin={mapOrigin} destination={place.name} />
                            </div>

                            {/* SURVIVAL GRID */}
                            <SurvivalGrid
                              lat={place.coordinates?.lat || 10.85}
                              lng={place.coordinates?.lng || 76.27}
                            />

                            {/* PLAN B SWAP */}
                            {place.alternativePlace && (
                              <div className="mt-6 sm:mt-8 bg-white/5 border border-white/10 p-4 sm:p-6 md:p-8 rounded-2xl sm:rounded-[2rem] md:rounded-[2.5rem] shadow-xl group/alt hover:bg-slate-900/50 transition-all">
                                <p className="text-yellow-500 text-[8px] sm:text-[9px] md:text-[10px] font-black uppercase tracking-widest mb-3 sm:mb-4 flex items-center gap-2"><RefreshCw className="w-3 h-3" /> Smart Swap Suggestion</p>
                                <div className="flex flex-col sm:flex-row justify-between items-center gap-4 sm:gap-6">
                                  <p className="text-base sm:text-lg md:text-xl font-bold text-white/90 italic">"{place.alternativePlace}"</p>
                                  <button onClick={() => onSwitchPlan(day.dayNumber, place.name, place.alternativePlace)} className="group/btn relative overflow-hidden w-full sm:w-auto bg-gradient-to-r from-blue-600/10 via-purple-600/10 to-blue-600/10 hover:from-blue-600/25 hover:via-purple-600/25 hover:to-blue-600/25 text-white/80 hover:text-white border border-white/10 hover:border-blue-400/30 px-6 sm:px-10 py-3 sm:py-4 rounded-xl sm:rounded-2xl font-black text-[9px] sm:text-[10px] uppercase tracking-widest whitespace-nowrap shrink-0 transition-all duration-500 active:scale-[0.97] shadow-lg hover:shadow-blue-500/20"><div className="absolute inset-0 bg-gradient-to-r from-transparent via-white/5 to-transparent translate-x-[-100%] group-hover/btn:translate-x-[100%] transition-transform duration-700"></div><span className="relative">Swap Plan</span></button>
                                </div>
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>

                {/* Sidebar: Nearby Highlights (only if data exists) */}
                {day.nearbyHighlights && highlightCategories.some(cat => day.nearbyHighlights?.[cat.key]) && (
                <aside className="w-full xl:w-96 bg-white/5 p-5 sm:p-8 md:p-12">
                   <h6 className="text-[10px] sm:text-xs font-black text-white/40 uppercase tracking-[0.3em] sm:tracking-[0.4em] mb-6 sm:mb-8 md:mb-12 flex items-center gap-2 sm:gap-3"><MapPin className="w-4 h-4 sm:w-5 sm:h-5 text-blue-400" /> Nearby Highlights</h6>
                   <div className="grid grid-cols-2 sm:grid-cols-4 xl:grid-cols-1 gap-3 sm:gap-4 md:gap-6">
                     {highlightCategories.map((cat) => {
                       const value = day.nearbyHighlights?.[cat.key];
                       if (!value) return null;
                       return (
                         <a
                           key={cat.key}
                           href={`https://www.google.com/maps/search/${encodeURIComponent(value + ', ' + day.cityLocation)}`}
                           target="_blank"
                           rel="noreferrer"
                           className={`group/hl block bg-white/5 border border-white/10 rounded-xl sm:rounded-2xl p-3 sm:p-4 md:p-5 transition-all hover:border-white/20 ${cat.hoverBg} active:scale-95`}
                         >
                           <div className="flex items-center gap-2 sm:gap-3 mb-2 sm:mb-3">
                              <div className={`p-2 sm:p-3 rounded-lg sm:rounded-xl bg-white/5 border border-white/10 ${cat.color} group-hover/hl:scale-110 transition-transform shrink-0`}>
                                  {cat.icon}
                              </div>
                              <span className="text-[8px] sm:text-[9px] md:text-[10px] font-black text-white/30 uppercase tracking-[0.15em] sm:tracking-[0.3em]">{cat.label}</span>
                           </div>
                           <p className="text-xs sm:text-sm md:text-base font-bold text-white/90 leading-snug">{safeRender(value)}</p>
                           <p className="text-[7px] sm:text-[8px] text-white/20 font-bold uppercase mt-1 sm:mt-2 tracking-wider">Tap to navigate</p>
                         </a>
                       );
                     })}
                   </div>
                </aside>
                )}
              </div>
            </div>
          ))}
        </div>

        {/* FINANCIAL BREAKDOWN */}
        <section>
          <div className="bg-white/5 backdrop-blur-3xl rounded-2xl sm:rounded-[2.5rem] md:rounded-[3.5rem] border border-white/10 p-5 sm:p-8 md:p-12 shadow-2xl">
            <div className="flex items-center gap-3 sm:gap-4 mb-6 sm:mb-10 border-b border-white/5 pb-4 sm:pb-6"><Wallet className="text-emerald-400 w-6 h-6 sm:w-8 sm:h-8" /><h3 className="text-xl sm:text-2xl md:text-3xl font-black tracking-tight italic">Financial Logic</h3></div>
            <div className="space-y-3 sm:space-y-4">
              {itinerary.budgetAnalysis?.breakdown && Object.entries(itinerary.budgetAnalysis.breakdown)
                .filter(([key]) => !key.toLowerCase().includes('financial') && !key.toLowerCase().includes('warning'))
                .map(([key, val]) => (
                <div key={key} className="flex justify-between items-center bg-white/5 p-3 sm:p-4 md:p-5 rounded-xl sm:rounded-2xl border border-white/5 hover:bg-white/10 transition-all">
                   <span className="capitalize font-black text-white/40 text-[9px] sm:text-[10px] tracking-widest">{key}</span>
                   <span className="font-bold text-sm sm:text-base md:text-lg">{safeRender(val)}</span>
                </div>
              ))}
            </div>

            {/* Financial Warning — Isolated Card */}
            {itinerary.budgetAnalysis?.breakdown && Object.entries(itinerary.budgetAnalysis.breakdown)
              .filter(([key]) => key.toLowerCase().includes('financial') || key.toLowerCase().includes('warning'))
              .map(([key, val]) => (
                <div key={key} className="mt-5 sm:mt-8 bg-gradient-to-r from-amber-500/10 to-orange-500/10 backdrop-blur-xl border border-amber-500/20 rounded-xl sm:rounded-[1.5rem] p-4 sm:p-6 md:p-8 shadow-xl">
                  <div className="flex items-center gap-2 sm:gap-3 mb-3 sm:mb-4">
                    <div className="bg-amber-400/20 p-2 sm:p-2.5 rounded-lg sm:rounded-xl">
                      <Info className="w-4 h-4 sm:w-5 sm:h-5 text-amber-400" />
                    </div>
                    <span className="text-amber-400 text-[9px] sm:text-[10px] font-black uppercase tracking-[0.2em] sm:tracking-[0.3em]">Financial Advisor Note</span>
                  </div>
                  <p className="text-amber-50/80 text-xs sm:text-sm md:text-base leading-relaxed italic">{safeRender(val)}</p>
                </div>
            ))}
          </div>
        </section>

        {/* FINAL BUDGET FOOTER */}
        <footer className="text-center py-8 sm:py-10 md:py-16 relative">
          <div className="absolute inset-0 bg-gradient-to-r from-blue-600/10 via-emerald-500/10 to-blue-600/10 blur-[80px] sm:blur-[100px] rounded-full"></div>
          <div className="relative inline-block bg-slate-950/60 backdrop-blur-3xl border border-white/10 px-6 sm:px-10 md:px-16 py-5 sm:py-6 md:py-8 rounded-2xl sm:rounded-[2rem] md:rounded-[3rem] shadow-2xl">
            <p className="text-white/30 text-[9px] sm:text-[10px] md:text-[11px] font-medium uppercase tracking-[0.4em] sm:tracking-[0.7em] mb-3 sm:mb-4">Total Trip Valuation</p>
            <p className="text-2xl sm:text-3xl md:text-4xl font-black tracking-tighter bg-clip-text text-transparent bg-gradient-to-b from-white via-white/80 to-white/20 drop-shadow-2xl italic uppercase">{safeRender(itinerary.estimatedTotalCost)}</p>
            <div className="mt-4 sm:mt-5 flex items-center justify-center gap-2 sm:gap-3 text-[8px] sm:text-[9px] md:text-[10px] font-bold text-emerald-400/60 tracking-[0.2em] sm:tracking-[0.3em] uppercase"><CheckCircle2 className="w-3 h-3 animate-pulse" /> Sanchaara Precision Intel</div>
          </div>
        </footer>
      </main>

      {/* ═══════ SMART PACKING LIST OVERLAY ═══════ */}
      {showPackingList && (
        <div className="fixed inset-0 z-[100] flex items-end sm:items-center justify-center">
          <div className="absolute inset-0 bg-black/70 backdrop-blur-sm" onClick={() => setShowPackingList(false)}></div>
          <div className="relative w-full sm:w-[480px] max-h-[85vh] sm:max-h-[80vh] flex flex-col rounded-t-3xl sm:rounded-3xl overflow-hidden border border-white/10 shadow-[0_-10px_60px_rgba(0,0,0,0.6)]"
            style={{ background: 'linear-gradient(180deg, rgba(12,20,37,0.98) 0%, rgba(8,14,28,0.99) 100%)' }}
          >
            {/* Header */}
            <div className="relative px-6 py-5 border-b border-white/5 shrink-0">
              <div className="absolute -top-10 -left-10 w-28 h-28 bg-emerald-500/10 rounded-full blur-3xl"></div>
              <div className="relative flex items-center justify-between">
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-emerald-500/15 border border-emerald-500/20 flex items-center justify-center">
                    <Backpack className="w-5 h-5 text-emerald-400" />
                  </div>
                  <div>
                    <h3 className="text-xs font-black text-white uppercase tracking-[0.2em]">Smart Packing List</h3>
                    <p className="text-[9px] text-white/30 font-medium tracking-wider mt-0.5">
                      {packingData ? `${packingData.categories?.reduce((a, c) => a + c.items.length, 0)} items` : 'Generating...'}
                      {packingData && ` · ${Object.values(checkedItems).filter(Boolean).length} packed`}
                    </p>
                  </div>
                </div>
                <button onClick={() => setShowPackingList(false)} className="w-8 h-8 rounded-lg bg-white/5 hover:bg-white/10 border border-white/5 flex items-center justify-center transition-all active:scale-90">
                  <X className="w-3.5 h-3.5 text-white/40" />
                </button>
              </div>
            </div>

            {/* Content */}
            <div className="flex-1 overflow-y-auto px-5 py-4 space-y-5" style={{ scrollbarWidth: 'none' }}>
              {packingLoading && (
                <div className="flex flex-col items-center justify-center py-16 gap-4">
                  <Loader2 className="w-8 h-8 text-emerald-400 animate-spin" />
                  <p className="text-[10px] font-black text-white/30 uppercase tracking-[0.3em]">Analyzing your trip...</p>
                </div>
              )}

              {packingData?.categories?.map((cat, catIdx) => (
                <div key={catIdx} className="bg-white/[0.02] border border-white/[0.06] rounded-2xl p-4 space-y-2">
                  <div className="flex items-center gap-2.5 mb-3">
                    <div className="w-8 h-8 rounded-lg bg-white/5 border border-white/10 flex items-center justify-center text-emerald-400">
                      {packingIcons[cat.icon] || <Backpack className="w-4 h-4" />}
                    </div>
                    <span className="text-[10px] font-black text-white/50 uppercase tracking-[0.2em]">{cat.name}</span>
                    <span className="ml-auto text-[9px] text-white/20 font-bold">
                      {cat.items.filter((_, i) => checkedItems[`${catIdx}-${i}`]).length}/{cat.items.length}
                    </span>
                  </div>
                  {cat.items.map((item, itemIdx) => {
                    const isChecked = checkedItems[`${catIdx}-${itemIdx}`];
                    return (
                      <button
                        key={itemIdx}
                        onClick={() => toggleCheck(catIdx, itemIdx)}
                        className={`w-full flex items-center gap-3 px-3 py-2.5 rounded-xl transition-all duration-300 text-left group ${
                          isChecked ? 'bg-emerald-500/10 border border-emerald-500/15' : 'hover:bg-white/[0.03] border border-transparent'
                        }`}
                      >
                        <div className={`w-5 h-5 rounded-md flex items-center justify-center shrink-0 transition-all duration-300 ${
                          isChecked ? 'bg-emerald-500 border-emerald-400' : 'border border-white/15 bg-transparent'
                        }`}>
                          {isChecked && <Check className="w-3 h-3 text-white" />}
                        </div>
                        <span className={`text-[12px] font-medium transition-all duration-300 ${
                          isChecked ? 'text-white/30 line-through' : 'text-white/70'
                        }`}>
                          {item}
                        </span>
                      </button>
                    );
                  })}
                </div>
              ))}
            </div>

            {/* Footer progress */}
            {packingData && (
              <div className="px-6 py-4 border-t border-white/5 shrink-0">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-[9px] font-black text-white/30 uppercase tracking-wider">Packing Progress</span>
                  <span className="text-[10px] font-black text-emerald-400">
                    {Math.round((Object.values(checkedItems).filter(Boolean).length / packingData.categories?.reduce((a, c) => a + c.items.length, 0)) * 100) || 0}%
                  </span>
                </div>
                <div className="h-1.5 bg-white/5 rounded-full overflow-hidden">
                  <div
                    className="h-full bg-gradient-to-r from-emerald-500 to-cyan-400 rounded-full transition-all duration-500"
                    style={{ width: `${(Object.values(checkedItems).filter(Boolean).length / (packingData.categories?.reduce((a, c) => a + c.items.length, 0) || 1)) * 100}%` }}
                  ></div>
                </div>
              </div>
            )}
          </div>
        </div>
      )}

    </div>
  );
}