import React, { useState } from 'react';
import MapComponent from './MapComponent';
import jsPDF from 'jspdf';
import CrowdAnalyzer from './CrowdAnalyzer';
import SurvivalGrid from './SurvivalGrid';
import { 
  Download, RefreshCw, Zap, Wind, Utensils, 
  Film, Gamepad2, Navigation, Clock, CheckCircle2,
  Share2, Wallet, Users, TrendingUp, Info 
} from 'lucide-react';

export default function ItineraryDisplay({ itinerary, onEdit, onSwitchPlan }) {
  const [isGenerating, setIsGenerating] = useState(false);

  if (!itinerary || !itinerary.days || !itinerary.initialLogistics) return null;

  // --- HELPER: SAFE RENDERER (Prevents Object-as-child crash) ---
  const safeRender = (data) => {
    if (!data) return "";
    if (typeof data === 'string' || typeof data === 'number') return data;
    if (typeof data === 'object') return data.name || data.value || data.text || JSON.stringify(data);
    return "";
  };

  // --- PHASE 10: WHATSAPP FORMATTING ---
  const shareToWhatsApp = () => {
    let text = `*🌴 SANCHAARA AI: MY INDIAN ODYSSEY* 🇮🇳\n\n`;
    text += `*Route:* ${itinerary.initialLogistics.from} ➔ ${itinerary.days[0].cityLocation}\n`;
    text += `*Total Investment:* ${renderBudget(itinerary.estimatedTotalCost)}\n`;
    text += `*Per Head Share:* ${itinerary.budgetAnalysis?.perPerson || 'N/A'}\n\n`;
    
    itinerary.days.forEach(day => {
      text += `*📅 ${day.date || 'Day ' + day.dayNumber}*\n`;
      day.places.forEach(p => text += `• ${p.name} (_Arr: ${p.time}_)\n`);
      text += `\n`;
    });
    
    text += `_Plan generated by Sanchaara AI_`;
    const encodedText = encodeURIComponent(text);
    window.open(`https://wa.me/?text=${encodedText}`, '_blank');
  };

  // --- PROFESSIONAL VECTOR PDF GENERATOR ---
  const exportPDF = () => {
    setIsGenerating(true);
    const doc = new jsPDF();
    let yPos = 20;

    const checkPage = (height) => {
      if (yPos + height > 280) { doc.addPage(); yPos = 20; return true; }
      return false;
    };

    // Header
    doc.setFillColor(15, 23, 42); 
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text('SANCHAARA AI: TRIP DOSSIER', 20, 25);
    doc.setFontSize(10);
    doc.text(`Estimated Total: ${renderBudget(itinerary.estimatedTotalCost)}`, 20, 32);

    yPos = 55;
    itinerary.days.forEach((day, dIdx) => {
      checkPage(40);
      doc.setFillColor(240, 245, 255);
      doc.rect(20, yPos, 170, 10, 'F');
      doc.setTextColor(37, 99, 235);
      doc.text(`DAY ${dIdx + 1}: ${day.cityLocation} (${day.date || ''})`, 25, yPos + 7);
      yPos += 15;

      day.places.forEach((place) => {
        const desc = doc.splitTextToSize(place.description, 160);
        checkPage(25 + (desc.length * 5));
        doc.setTextColor(0, 0, 0);
        doc.setFont("helvetica", "bold");
        doc.text(`• ${place.name} (${place.time})`, 25, yPos);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 100, 100);
        doc.text(desc, 25, yPos + 6);
        yPos += (desc.length * 5) + 15;
      });
      yPos += 10;
    });

    doc.save(`Sanchaara-Odyssey-${itinerary.days[0].cityLocation}.pdf`);
    setIsGenerating(false);
  };

  const getTrafficDetails = (status) => {
    const s = status?.toLowerCase() || '';
    if (s.includes('high')) return { color: 'text-red-400', bg: 'bg-red-500/20', label: 'HEAVY' };
    if (s.includes('moderate')) return { color: 'text-yellow-400', bg: 'bg-yellow-500/20', label: 'MODERATE' };
    return { color: 'text-emerald-400', bg: 'bg-emerald-500/20', label: 'CLEAR' };
  };

  const renderBudget = (budget) => {
    if (typeof budget === 'object' && budget !== null) {
      return `₹${budget.value || budget.total || 'Calculated'}`;
    }
    return budget;
  };

  return (
    <div className="min-h-screen w-full p-2 md:p-8 animate-fade-in relative z-10 text-white font-sans selection:bg-emerald-500/30">
      
      {/* 🧭 NAVIGATION (Responsive) */}
      <nav className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center mb-10 gap-6 bg-white/5 backdrop-blur-2xl p-4 md:p-6 rounded-[2rem] md:rounded-[2.5rem] border border-white/10 shadow-2xl">
        <div className="text-center md:text-left">
          <h2 className="text-3xl md:text-4xl font-black tracking-tighter italic">SANCHAARA <span className="text-blue-400 font-normal">AI</span></h2>
          <p className="text-[8px] md:text-[9px] font-bold uppercase tracking-[0.4em] text-white/40">Intelligent Journey Partner</p>
        </div>

        <div className="flex flex-wrap justify-center items-center gap-3">
          <button onClick={shareToWhatsApp} className="flex items-center gap-2 bg-[#25D366] hover:bg-[#128C7E] text-white px-4 py-2 md:px-5 md:py-3 rounded-2xl font-black text-[9px] md:text-[10px] uppercase tracking-widest transition-all">
            <Share2 className="w-4 h-4" /> Share
          </button>
          <button onClick={onEdit} className="p-3 bg-white/5 hover:bg-white/10 rounded-2xl transition-all border border-white/10">
            <RefreshCw className="w-5 h-5 text-white/60" />
          </button>
          <button onClick={exportPDF} disabled={isGenerating} className="flex items-center gap-2 bg-white text-black px-4 py-2 md:px-6 md:py-3 rounded-2xl font-black text-[9px] md:text-[10px] uppercase tracking-widest shadow-xl">
            <Download className="w-4 h-4" /> {isGenerating ? 'PDF...' : 'PDF'}
          </button>
        </div>
      </nav>

      {/* 🚀 PHASE 9: LOCAL PULSE & SEASONAL INSIGHT */}
      <div className="max-w-7xl mx-auto space-y-6 mb-16">
        {itinerary.seasonalNote && (
          <div className="bg-gradient-to-r from-amber-500/20 to-orange-600/20 backdrop-blur-xl border border-amber-500/30 p-6 md:p-8 rounded-[2rem] md:rounded-[2.5rem] shadow-2xl flex flex-col md:flex-row items-center gap-6 md:gap-8 group">
            <div className="bg-amber-400 text-black w-16 h-16 md:w-20 md:h-20 rounded-3xl flex items-center justify-center text-3xl md:text-4xl shadow-xl font-bold animate-pulse">💡</div>
            <div className="text-center md:text-left">
              <span className="bg-amber-400/20 text-amber-400 text-[10px] font-black uppercase tracking-[0.3em] px-3 py-1 rounded-full border border-amber-400/20">Seasonal Intelligence</span>
              <p className="text-amber-50/80 text-base md:text-lg font-medium italic mt-3 leading-relaxed">"{itinerary.seasonalNote}"</p>
            </div>
          </div>
        )}

        {itinerary.localPulse && (
          <div className="overflow-hidden bg-blue-500/10 border-y border-white/5 backdrop-blur-md py-4 rounded-2xl relative">
            <div className="flex animate-marquee whitespace-nowrap gap-20">
              {itinerary.localPulse.map((event, i) => (
                <span key={i} className="flex items-center gap-3 text-blue-300 font-black text-[10px] md:text-[11px] uppercase tracking-[0.3em]">
                  <TrendingUp className="w-5 h-5 text-green-400" /> {safeRender(event)}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>

      <main className="max-w-7xl mx-auto space-y-20">
        
        {/* ✈️ DEPARTURE SECTION */}
        <section className="bg-white/5 backdrop-blur-xl rounded-[2rem] md:rounded-[3rem] border border-white/10 shadow-2xl overflow-hidden grid grid-cols-1 lg:grid-cols-3">
          <div className="p-8 md:p-10 lg:col-span-1 flex flex-col justify-center border-b lg:border-b-0 lg:border-r border-white/5">
            <span className="text-blue-400 font-black text-[10px] tracking-widest uppercase mb-4 flex items-center gap-2"><Navigation className="w-3 h-3" /> Initial Transit</span>
            <h3 className="text-3xl md:text-4xl font-black mb-8 leading-tight tracking-tighter text-center lg:text-left">
              {itinerary.initialLogistics.from} <br className="hidden lg:block" />
              <span className="text-white/20 text-2xl font-light">➔</span> {itinerary.initialLogistics.to}
            </h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-white/5 p-4 rounded-2xl border border-white/5 text-center">
                <p className="text-white/30 text-[9px] font-bold uppercase mb-1">Mode</p>
                <p className="font-black text-xs uppercase text-blue-400">{itinerary.initialLogistics.mode}</p>
              </div>
              <div className="bg-white/5 p-4 rounded-2xl border border-white/5 text-center">
                <p className="text-white/30 text-[9px] font-bold uppercase mb-1">Dist.</p>
                <p className="font-black text-xs text-green-400 uppercase">{itinerary.initialLogistics.distance}</p>
              </div>
            </div>
          </div>
          <div className="lg:col-span-2 h-[300px] md:h-[350px]">
            <MapComponent origin={itinerary.initialLogistics.from} destination={itinerary.initialLogistics.to} isFlight={true} />
          </div>
        </section>

        {/* 📅 DAILY CARDS (Responsive Layout) */}
        <div className="space-y-16 md:space-y-24">
          {itinerary.days.map((day, dayIdx) => (
            <div key={dayIdx} className="bg-white/5 backdrop-blur-3xl rounded-[2rem] md:rounded-[3.5rem] border border-white/10 shadow-2xl overflow-hidden">
              <div className="bg-gradient-to-r from-blue-600/20 to-emerald-500/10 p-6 md:p-8 border-b border-white/5 flex flex-col md:flex-row justify-between items-center gap-6">
                <div className="flex items-center gap-4 md:gap-6">
                  <div className="w-12 h-12 md:w-16 md:h-16 bg-blue-600 text-white rounded-2xl md:rounded-3xl flex flex-col items-center justify-center shadow-lg">
                    <span className="text-[8px] md:text-[10px] font-black uppercase opacity-60">Day</span>
                    <span className="text-xl md:text-3xl font-black leading-none">{dayIdx + 1}</span>
                  </div>
                  <div>
                    <p className="text-blue-400 text-[9px] md:text-[10px] font-black uppercase tracking-[0.2em]">{day.date}</p>
                    <h4 className="text-2xl md:text-4xl font-black tracking-tighter">{day.cityLocation}</h4>
                  </div>
                </div>
                <div className="bg-white/5 px-5 py-3 md:px-6 md:py-4 rounded-2xl md:rounded-3xl border border-white/10 flex items-center gap-4">
                   <span className="text-3xl md:text-4xl">{day.weather?.icon || "🌤️"}</span>
                   <div className="text-right">
                     <p className="text-xl md:text-2xl font-black tracking-tighter">{day.weather?.temp}</p>
                     <p className="text-[8px] md:text-[9px] font-black uppercase text-white/40 tracking-widest">{day.weather?.condition}</p>
                   </div>
                </div>
              </div>

              <div className="flex flex-col xl:flex-row">
                <div className="flex-[2.5] p-6 md:p-14 space-y-24 md:space-y-32 border-b xl:border-b-0 xl:border-r border-white/5">
                  {day.places?.map((place, pIdx) => {
                    const traffic = getTrafficDetails(place.trafficStatus);
                    const mapOrigin = pIdx === 0 
                        ? (dayIdx === 0 ? itinerary.arrivalLogistics.from : "Hotel in " + day.cityLocation) 
                        : day.places[pIdx - 1].name;

                    return (
                      <div key={pIdx} className="group relative">
                        <div className="flex flex-col md:flex-row gap-8 md:gap-12">
                          
                          {/* 🕒 TIME & TRAFFIC SECTION (Responsive Width) */}
                          <div className="w-full md:w-52 shrink-0 flex flex-col">
                             <div className="flex items-center gap-2 text-blue-400 mb-2">
                                <Clock className="w-4 h-4 animate-pulse" />
                                <span className="text-[10px] md:text-[11px] font-black uppercase tracking-[0.2em]">Arrival</span>
                             </div>
                             <p className="text-2xl md:text-3xl font-black text-white tracking-tight leading-tight">{place.time}</p>
                             <div className={`inline-flex items-center self-start gap-2 mt-4 px-3 py-1.5 rounded-xl text-[9px] font-black ${traffic.bg} ${traffic.color} border border-white/5`}>
                               <span className="w-1.5 h-1.5 rounded-full bg-current"></span>
                               {traffic.label} TRAFFIC
                             </div>
                             <div className="mt-4 bg-white/5 border border-white/10 rounded-xl px-4 py-2 self-start">
                                <p className="text-[8px] font-bold text-white/30 uppercase tracking-widest mb-1">Route</p>
                                <p className="text-[10px] font-black text-green-400 whitespace-nowrap">
                                  🚗 {pIdx === 0 && dayIdx === 0 ? itinerary.arrivalLogistics.distance : (place.distanceFromPrevious || 'Local')}
                                </p>
                             </div>
                          </div>

                          <div className="flex-1 min-w-0">
                            <h5 className="text-3xl md:text-4xl font-black text-white mb-6 tracking-tight leading-tight group-hover:text-blue-300 transition-all break-words">{place.name}</h5>
                            
                            {/* 📊 CROWD ANALYZER */}
                            <CrowdAnalyzer analysis={place.crowdAnalysis} />

                            <p className="text-white/60 my-8 leading-relaxed italic text-base md:text-lg border-l-2 border-blue-500/30 pl-6 py-1">{place.description}</p>
                            
                            <div className="rounded-[2rem] md:rounded-[2.5rem] overflow-hidden border border-white/10 h-64 md:h-80 transition-all shadow-2xl">
                              <MapComponent origin={mapOrigin} destination={place.name} />
                            </div>

                            {/* 🛡️ SURVIVAL GRID */}
    <SurvivalGrid 
      lat={place.coordinates?.lat || 10.85} 
      lng={place.coordinates?.lng || 76.27} 
    />                            
                            {/* PLAN B SWAP */}
                            {place.alternativePlace && (
                              <div className="mt-8 bg-white/5 border border-white/10 p-6 md:p-8 rounded-[2rem] md:rounded-[2.5rem] shadow-xl group/alt hover:bg-slate-900/50 transition-all">
                                <p className="text-yellow-500 text-[9px] md:text-[10px] font-black uppercase tracking-widest mb-4 flex items-center gap-2"><RefreshCw className="w-3 h-3" /> Smart Swap Suggestion</p>
                                <div className="flex flex-col md:flex-row justify-between items-center gap-6">
                                  <p className="text-lg md:text-xl font-bold text-white/90 italic">"{place.alternativePlace}"</p>
                                  <button onClick={() => onSwitchPlan(day.dayNumber, place.name, place.alternativePlace)} className="w-full md:w-auto bg-white text-black px-10 py-4 rounded-2xl font-black text-[10px] uppercase shadow-lg hover:bg-green-400 active:scale-95 transition-all">Swap Plan</button>
                                </div>
                              </div>
                            )}
                          </div>
                        </div>
                      </div>
                    );
                  })}
                </div>

                {/* Sidebar (Daily Dose) */}
                <aside className="w-full xl:w-96 bg-white/5 p-8 md:p-12">
                   <h6 className="text-xs font-black text-white/40 uppercase tracking-[0.4em] mb-12 flex items-center gap-3"><Wind className="w-5 h-5 text-blue-400" /> Daily Dose</h6>
                   <div className="grid grid-cols-1 md:grid-cols-3 xl:grid-cols-1 gap-12">
                     {['recipe', 'movie', 'game'].map((item) => (
                       <div key={item} className="group/dose">
                         <div className="flex items-center gap-4 mb-4">
                            <div className="p-4 rounded-2xl bg-white/5 border border-white/10 shadow-xl group-hover/dose:scale-110 transition-transform">
                                {item === 'recipe' ? <Utensils className="w-5 h-5 text-orange-400" /> : item === 'movie' ? <Film className="w-5 h-5 text-blue-400" /> : <Gamepad2 className="w-5 h-5 text-emerald-400" />}
                            </div>
                            <span className="text-[10px] font-black text-white/20 uppercase tracking-[0.3em]">{item}</span>
                         </div>
                         <p className="text-lg font-bold text-white/90">{safeRender(day.dailyDose?.[item])}</p>
                       </div>
                     ))}
                   </div>
                </aside>
              </div>
            </div>
          ))}
        </div>

        {/* --- PHASE 10: FINANCIAL BREAKDOWN (Responsive Grid) --- */}
        <section className="grid grid-cols-1 md:grid-cols-2 gap-8 md:gap-10">
          <div className="bg-white/5 backdrop-blur-3xl rounded-[2.5rem] md:rounded-[3.5rem] border border-white/10 p-8 md:p-12 shadow-2xl">
            <div className="flex items-center gap-4 mb-10 border-b border-white/5 pb-6"><Wallet className="text-emerald-400 w-8 h-8" /><h3 className="text-2xl md:text-3xl font-black tracking-tight italic">Financial Logic</h3></div>
            <div className="space-y-4">
              {itinerary.budgetAnalysis?.breakdown && Object.entries(itinerary.budgetAnalysis.breakdown).map(([key, val]) => (
                <div key={key} className="flex justify-between items-center bg-white/5 p-5 rounded-2xl border border-white/5 hover:bg-white/10 transition-all">
                   <span className="capitalize font-black text-white/40 text-[10px] tracking-widest">{key}</span>
                   <span className="font-bold text-base md:text-lg">{safeRender(val)}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-gradient-to-br from-indigo-600/20 to-blue-600/20 backdrop-blur-3xl rounded-[2.5rem] md:rounded-[3.5rem] border border-white/10 p-8 md:p-12 shadow-2xl flex flex-col justify-center text-center items-center">
             <div className="bg-white/10 p-6 rounded-full mb-8"><Users className="w-12 h-12 text-blue-400" /></div>
             <p className="text-blue-300 font-black text-[11px] uppercase tracking-[0.4em] mb-4">Investment Per Head</p>
             <h4 className="text-5xl md:text-7xl font-black tracking-tighter mb-4 text-white">{safeRender(itinerary.budgetAnalysis?.perPerson)}</h4>
             <p className="text-white/30 text-xs md:text-sm max-w-[280px] leading-relaxed italic">Estimated share based on group size.</p>
          </div>
        </section>

        {/* 💰 FINAL BUDGET FOOTER */}
        <footer className="text-center py-20 md:py-40 relative">
          <div className="absolute inset-0 bg-gradient-to-r from-blue-600/10 via-emerald-500/10 to-blue-600/10 blur-[140px] rounded-full"></div>
          <div className="relative inline-block bg-slate-950/60 backdrop-blur-3xl border border-white/10 px-8 md:px-24 py-8 md:py-12 rounded-[2.5rem] md:rounded-[4rem] shadow-2xl">
            <p className="text-white/30 text-[10px] md:text-[11px] font-medium uppercase tracking-[0.7em] mb-6">Total Trip Valuation</p>
            <p className="text-4xl md:text-4xl font-black tracking-tighter bg-clip-text text-transparent bg-gradient-to-b from-white via-white/80 to-white/20 drop-shadow-2xl italic uppercase">{safeRender(itinerary.estimatedTotalCost)}</p>
            <div className="mt-8 flex items-center justify-center gap-3 text-[9px] md:text-[10px] font-bold text-emerald-400/60 tracking-[0.3em] uppercase"><CheckCircle2 className="w-3 h-3 animate-pulse" /> Sanchaara Precision Intel</div>
          </div>
        </footer>
      </main>
    </div>
  );
}