import React, { useState } from 'react';
import MapComponent from './MapComponent';
import jsPDF from 'jspdf';
import CrowdAnalyzer from './CrowdAnalyzer';
import SurvivalGrid from './SurvivalGrid';
import { 
  Download, RefreshCw, Zap, Wind, Utensils, 
  Film, Gamepad2, Navigation, Clock, CheckCircle2,
  Share2, Wallet, Users, TrendingUp, Info 
} from 'lucide-react';

export default function ItineraryDisplay({ itinerary, onEdit, onSwitchPlan }) {
  const [isGenerating, setIsGenerating] = useState(false);

  if (!itinerary || !itinerary.days || !itinerary.initialLogistics) return null;

  // --- 1. WHATSAPP SHARE LOGIC (Phase 10) ---
  const shareToWhatsApp = () => {
    let text = `* SANCHAARA AI: MY INDIAN ODYSSEY* \n\n`;
    text += `*Route:* ${itinerary.initialLogistics.from} ➔ ${itinerary.days[0].cityLocation}\n`;
    text += `*Duration:* ${itinerary.days.length} Days\n`;
    text += `*Total Investment:* ${renderBudget(itinerary.estimatedTotalCost)}\n`;
    text += `*Per Head Share:* ${itinerary.budgetAnalysis?.perPerson || 'N/A'}\n\n`;
    
    itinerary.days.forEach(day => {
      text += `*📅 ${day.date || 'Day ' + day.dayNumber}*\n`;
      day.places.forEach(p => text += `• ${p.name} (_Arr: ${p.time}_)\n`);
      text += `\n`;
    });
    
    text += `_Plan generated by Sanchaara AI - Your Intelligent Journey Partner_`;
    const encodedText = encodeURIComponent(text);
    window.open(`https://wa.me/?text=${encodedText}`, '_blank');
  };

  // --- 2. PROFESSIONAL PDF GENERATOR (Vector-Based) ---
  const exportPDF = () => {
    setIsGenerating(true);
    const doc = new jsPDF();
    let yPos = 20;

    // Helper to check page overflow
    const checkPage = (heightNeeded) => {
      if (yPos + heightNeeded > 280) {
        doc.addPage();
        yPos = 20;
      }
    };

    // Header Branding
    doc.setFillColor(15, 23, 42); 
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(22);
    doc.setFont("helvetica", "bold");
    doc.text('SANCHAARA AI: TRIP DOSSIER', 20, 25);
    doc.setFontSize(10);
    doc.setFont("helvetica", "normal");
    doc.text(`Generated on: ${new Date().toLocaleDateString()} | Total Budget: ${renderBudget(itinerary.estimatedTotalCost)}`, 20, 32);

    yPos = 55;

    // Logistics Section
    doc.setTextColor(34, 197, 94);
    doc.setFontSize(14);
    doc.text('TRANSIT LOGISTICS', 20, yPos);
    doc.setTextColor(80, 80, 80);
    doc.setFontSize(10);
    doc.text(`Origin: ${itinerary.initialLogistics.from} -> Gateway: ${itinerary.initialLogistics.to}`, 20, yPos + 8);
    doc.text(`Mode: ${itinerary.initialLogistics.mode} | Distance: ${itinerary.initialLogistics.distance}`, 20, yPos + 14);
    yPos += 30;

    // Itinerary Loop
    itinerary.days.forEach((day, dIdx) => {
      checkPage(40);
      doc.setFillColor(240, 245, 255);
      doc.rect(20, yPos, 170, 10, 'F');
      doc.setTextColor(37, 99, 235);
      doc.setFont("helvetica", "bold");
      doc.text(`DAY ${dIdx + 1}: ${day.cityLocation} (${day.date || ''})`, 25, yPos + 7);
      yPos += 15;

      day.places.forEach((place) => {
        const desc = doc.splitTextToSize(place.description, 160);
        checkPage(20 + (desc.length * 5));
        
        doc.setTextColor(0, 0, 0);
        doc.setFont("helvetica", "bold");
        doc.text(`• ${place.name} (Arrival: ${place.time})`, 25, yPos);
        
        doc.setFont("helvetica", "normal");
        doc.setTextColor(100, 100, 100);
        doc.text(desc, 25, yPos + 6);
        yPos += (desc.length * 5) + 12;
      });
      yPos += 10;
    });

    // Budget Analysis
    checkPage(40);
    doc.setFillColor(15, 23, 42);
    doc.rect(20, yPos, 170, 25, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.text(`TOTAL ESTIMATED INVESTMENT: ${renderBudget(itinerary.estimatedTotalCost)}`, 25, yPos + 10);
    doc.text(`SHARE PER PERSON: ${itinerary.budgetAnalysis?.perPerson || 'N/A'}`, 25, yPos + 18);

    doc.save(`Sanchaara-Trip-Plan.pdf`);
    setIsGenerating(false);
  };

  const getTrafficDetails = (status) => {
    const s = status?.toLowerCase() || '';
    if (s.includes('high')) return { color: 'text-red-400', bg: 'bg-red-500/20', label: 'HEAVY' };
    if (s.includes('moderate')) return { color: 'text-yellow-400', bg: 'bg-yellow-500/20', label: 'MODERATE' };
    return { color: 'text-emerald-400', bg: 'bg-emerald-500/20', label: 'CLEAR' };
  };

  const renderBudget = (budget) => {
    if (typeof budget === 'object' && budget !== null) {
      return `₹${budget.value || budget.total || 'Calculated'}`;
    }
    return budget;
  };

  return (
    <div className="min-h-screen w-full p-4 md:p-8 animate-fade-in relative z-10 text-white font-sans selection:bg-emerald-500/30">
      
      {/* 🧭 NAVIGATION */}
      <nav className="max-w-7xl mx-auto flex flex-col md:flex-row justify-between items-center mb-10 gap-6 bg-white/5 backdrop-blur-2xl p-6 rounded-[2.5rem] border border-white/10 shadow-2xl">
        <div>
          <h2 className="text-4xl font-black tracking-tighter italic text-white">SANCHAARA <span className="text-blue-400 font-normal">AI</span></h2>
          <p className="text-[9px] font-bold uppercase tracking-[0.4em] text-white/40">Your Intelligent Journey Partner</p>
        </div>

        <div className="flex items-center gap-3">
          <button onClick={shareToWhatsApp} className="flex items-center gap-2 bg-[#25D366] hover:bg-[#128C7E] text-white px-5 py-3 rounded-2xl font-black text-[10px] uppercase tracking-widest transition-all shadow-lg">
            <Share2 className="w-4 h-4" /> WhatsApp
          </button>
          <button onClick={onEdit} className="p-3 bg-white/5 hover:bg-white/10 rounded-2xl transition-all border border-white/10 group">
            <RefreshCw className="w-5 h-5 text-white/60 group-hover:rotate-180 transition-transform duration-500" />
          </button>
          <button onClick={exportPDF} disabled={isGenerating} className="flex items-center gap-2 bg-white text-black px-6 py-3 rounded-2xl font-black text-[10px] uppercase tracking-widest shadow-xl transition-all disabled:opacity-50">
            <Download className="w-4 h-4" /> {isGenerating ? 'Building PDF...' : 'Download PDF'}
          </button>
        </div>
      </nav>

      {/* 🚀 PHASE 9: LOCAL PULSE TICKER */}
      <div className="max-w-7xl mx-auto space-y-6 mb-16">
        {itinerary.seasonalNote && (
          <div className="bg-gradient-to-r from-amber-500/20 to-orange-600/20 backdrop-blur-xl border border-amber-500/30 p-8 rounded-[2.5rem] shadow-2xl flex flex-col md:flex-row items-center gap-8 group">
            <div className="bg-amber-400 text-black w-20 h-20 rounded-3xl flex items-center justify-center text-4xl shadow-xl font-bold animate-pulse">💡</div>
            <div>
              <span className="bg-amber-400/20 text-amber-400 text-[10px] font-black uppercase tracking-[0.3em] px-3 py-1 rounded-full border border-amber-400/20">Expert Intelligence</span>
              <h3 className="text-2xl font-black text-white tracking-tight mt-2">Local Insight for your Dates</h3>
              <p className="text-amber-50/80 text-lg font-medium italic mt-2 leading-relaxed italic">"{itinerary.seasonalNote}"</p>
            </div>
          </div>
        )}

        {itinerary.localPulse && (
          <div className="overflow-hidden bg-blue-500/10 border-y border-white/5 backdrop-blur-md py-4 rounded-2xl relative">
            <div className="flex animate-marquee whitespace-nowrap gap-20">
              {itinerary.localPulse.map((event, i) => (
                <span key={i} className="flex items-center gap-4 text-blue-300 font-black text-[11px] uppercase tracking-[0.3em]">
                  <TrendingUp className="w-5 h-5 text-green-400" /> {event}
                </span>
              ))}
            </div>
          </div>
        )}
      </div>

      <main className="max-w-7xl mx-auto space-y-20">
        
        {/* ✈️ DEPARTURE CARD */}
        <section className="bg-white/5 backdrop-blur-xl rounded-[3rem] border border-white/10 shadow-2xl overflow-hidden grid grid-cols-1 lg:grid-cols-3">
          <div className="p-10 lg:col-span-1 flex flex-col justify-center border-r border-white/5">
            <span className="text-blue-400 font-black text-[10px] tracking-widest uppercase mb-4 flex items-center gap-2"><Navigation className="w-3 h-3" /> Initial Transit</span>
            <h3 className="text-4xl font-black mb-8 leading-tight tracking-tighter">
              {itinerary.initialLogistics.from} <br/>
              <span className="text-white/20 text-2xl font-light">➔</span> {itinerary.initialLogistics.to}
            </h3>
            <div className="grid grid-cols-2 gap-4">
              <div className="bg-white/5 p-4 rounded-2xl border border-white/5 text-center">
                <p className="text-white/30 text-[9px] font-bold uppercase mb-1">Mode</p>
                <p className="font-black text-xs uppercase text-blue-400">{itinerary.initialLogistics.mode}</p>
              </div>
              <div className="bg-white/5 p-4 rounded-2xl border border-white/5 text-center">
                <p className="text-white/30 text-[9px] font-bold uppercase mb-1">Dist.</p>
                <p className="font-black text-xs text-green-400 uppercase">{itinerary.initialLogistics.distance}</p>
              </div>
            </div>
          </div>
          <div className="lg:col-span-2 h-[350px]">
            <MapComponent origin={itinerary.initialLogistics.from} destination={itinerary.initialLogistics.to} isFlight={true} />
          </div>
        </section>

        {/* 📅 DAILY CARDS */}
        <div className="space-y-24">
          {itinerary.days.map((day, dayIdx) => (
            <div key={dayIdx} className="bg-white/5 backdrop-blur-3xl rounded-[3.5rem] border border-white/10 shadow-2xl overflow-hidden">
              <div className="bg-gradient-to-r from-blue-600/20 to-emerald-500/10 p-8 border-b border-white/5 flex flex-col md:flex-row justify-between items-center gap-6 text-white">
                <div className="flex items-center gap-6">
                  <div className="w-16 h-16 bg-blue-600 text-white rounded-3xl flex flex-col items-center justify-center shadow-lg">
                    <span className="text-[10px] font-black uppercase opacity-60">Day</span>
                    <span className="text-3xl font-black leading-none">{dayIdx + 1}</span>
                  </div>
                  <div>
                    <p className="text-blue-400 text-[10px] font-black uppercase tracking-[0.2em]">{day.date}</p>
                    <h4 className="text-4xl font-black tracking-tighter">{day.cityLocation}</h4>
                  </div>
                </div>
                <div className="flex items-center gap-5 bg-white/5 px-6 py-4 rounded-3xl border border-white/10">
                   <span className="text-4xl">{day.weather?.icon || "🌤️"}</span>
                   <div className="text-right">
                     <p className="text-2xl font-black tracking-tighter">{day.weather?.temp}</p>
                     <p className="text-[9px] font-black uppercase text-white/40">{day.weather?.condition}</p>
                   </div>
                </div>
              </div>

              <div className="flex flex-col xl:flex-row">
                <div className="flex-[2.5] p-8 md:p-14 space-y-32 border-r border-white/5">
{day.places?.map((place, pIdx) => {
  const traffic = getTrafficDetails(place.trafficStatus);
  
  // Logic to determine where the user is coming from for the Map
  const mapOrigin = pIdx === 0 
      ? (dayIdx === 0 ? itinerary.arrivalLogistics.from : "Hotel in " + day.cityLocation) 
      : day.places[pIdx - 1].name;

  return (
    <div key={pIdx} className="group relative">
      <div className="flex flex-col md:flex-row gap-12">
        
        {/* 🕒 TIME SECTION */}
        <div className="md:w-60 shrink-0 flex flex-col">
           <div className="flex items-center gap-2 text-blue-400 mb-2">
              <Clock className="w-4 h-4 animate-pulse" />
              <span className="text-[11px] font-black uppercase tracking-[0.2em]">Arrival</span>
           </div>
           <p className="text-2xl md:text-3xl font-black text-white tracking-tight leading-tight">
              {place.time}
           </p>
           
           <div className={`inline-flex items-center self-start gap-2 mt-4 px-3 py-1.5 rounded-xl text-[9px] font-black ${traffic.bg} ${traffic.color} border border-white/5`}>
             <span className="w-1.5 h-1.5 rounded-full bg-current animate-pulse"></span>
             {traffic.label} TRAFFIC
           </div>
        </div>

        {/* ℹ️ MAIN CONTENT SECTION */}
        <div className="flex-1 min-w-0">
          <h5 className="text-4xl font-black text-white mb-6 tracking-tight leading-tight group-hover:text-blue-300 transition-all">
            {place.name}
          </h5>

          {/* 📊 NEW: CROWD ANALYZER COMPONENT */}
          <CrowdAnalyzer analysis={place.crowdAnalysis} />

          <p className="text-white/60 mt-6 mb-8 leading-relaxed italic text-lg border-l-2 border-blue-500/30 pl-6 py-1">
            {place.description}
          </p>
          
          {/* 🗺️ THE MAP COMPONENT */}
          <div className="rounded-[2.5rem] overflow-hidden border border-white/10 shadow-2xl transition-all hover:border-blue-500/30">
            <MapComponent origin={mapOrigin} destination={place.name} />
          </div>

          {/* 🛡️ NEW: SURVIVAL GRID (Safety & Essentials) */}
          {/* Passing the coordinates we added to the backend prompt */}
          <SurvivalGrid 
            lat={place.coordinates?.lat || 10.85} 
            lng={place.coordinates?.lng || 76.27} 
          />
          
          {/* PLAN B SWAP SECTION */}
          {place.alternativePlace && (
            <div className="mt-12 bg-white/5 border border-white/10 p-8 rounded-[2.5rem] shadow-xl group/alt transition-all hover:bg-slate-900/50">
              <p className="text-yellow-500 text-[10px] font-black uppercase tracking-widest mb-4 flex items-center gap-2">
                <RefreshCw className="w-3 h-3" /> Smart Swap Destination
              </p>
              <div className="flex flex-col md:flex-row justify-between items-center gap-6">
                <p className="text-xl font-bold text-white/90 italic">"{place.alternativePlace}"</p>
                <button 
                  onClick={() => onSwitchPlan(day.dayNumber, place.name, place.alternativePlace)}
                  className="bg-white text-black px-10 py-5 rounded-[1.5rem] font-black text-[10px] uppercase shadow-lg hover:bg-green-400 active:scale-95 transition-all"
                >
                  Swap Plan
                </button>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
})}
                </div>

                <aside className="flex-1 bg-white/5 p-12">
                   <h6 className="text-xs font-black text-white/40 uppercase tracking-[0.4em] mb-12 flex items-center gap-3">
                      <Wind className="w-5 h-5 text-blue-400" /> Daily Dose
                   </h6>
                   <div className="space-y-12">
                     {['recipe', 'movie', 'game'].map((item) => (
                       <div key={item} className="group/dose cursor-default">
                         <div className="flex items-center gap-4 mb-4">
                            <div className="p-4 rounded-2xl bg-white/5 border border-white/10 shadow-xl group-hover/dose:scale-110 transition-transform">
                                {item === 'recipe' ? <Utensils className="w-5 h-5 text-orange-400" /> : item === 'movie' ? <Film className="w-5 h-5 text-blue-400" /> : <Gamepad2 className="w-5 h-5 text-emerald-400" />}
                            </div>
                            <span className="text-[10px] font-black text-white/20 uppercase tracking-[0.3em]">{item}</span>
                         </div>
                         <p className="text-lg font-bold text-white/90 group-hover:text-white transition-colors">{day.dailyDose?.[item] || '...'}</p>
                       </div>
                     ))}
                   </div>
                </aside>
              </div>
            </div>
          ))}
        </div>

        {/* --- PHASE 10: FINANCIALS --- */}
        <section className="grid grid-cols-1 lg:grid-cols-2 gap-10">
          <div className="bg-white/5 backdrop-blur-3xl rounded-[3.5rem] border border-white/10 p-12 shadow-2xl">
            <div className="flex items-center gap-4 mb-10 border-b border-white/5 pb-6">
               <Wallet className="text-emerald-400 w-8 h-8" />
               <h3 className="text-3xl font-black tracking-tight italic">Expense Breakdown</h3>
            </div>
            <div className="space-y-4">
              {itinerary.budgetAnalysis?.breakdown && Object.entries(itinerary.budgetAnalysis.breakdown).map(([key, val]) => (
                <div key={key} className="flex justify-between items-center bg-white/5 p-5 rounded-2xl border border-white/5 group hover:bg-white/10 transition-all">
                   <span className="capitalize font-black text-white/40 text-[10px] tracking-widest">{key}</span>
                   <span className="font-bold text-lg text-white">{val}</span>
                </div>
              ))}
            </div>
          </div>

          <div className="bg-gradient-to-br from-indigo-600/20 to-blue-600/20 backdrop-blur-3xl rounded-[3.5rem] border border-white/10 p-12 shadow-2xl flex flex-col justify-center text-center items-center">
             <div className="bg-white/10 p-6 rounded-full mb-8 shadow-inner"><Users className="w-12 h-12 text-blue-400" /></div>
             <p className="text-blue-300 font-black text-[11px] uppercase tracking-[0.4em] mb-4">Investment Per Head</p>
             <h4 className="text-6xl md:text-7xl font-black tracking-tighter mb-4 text-white">{itinerary.budgetAnalysis?.perPerson}</h4>
             <p className="text-white/30 text-sm max-w-[280px] leading-relaxed italic">Estimated share based on group size.</p>
          </div>
        </section>

        {/* 💰 FOOTER BUDGET */}
        <footer className="text-center py-40 relative">
          <div className="absolute inset-0 bg-gradient-to-r from-blue-600/10 via-emerald-500/10 to-blue-600/10 blur-[140px] rounded-full animate-pulse"></div>
          <div className="relative inline-block bg-slate-950/60 backdrop-blur-3xl border border-white/10 px-24 py-12 rounded-[4rem] shadow-2xl">
            <p className="text-white/30 text-[11px] font-medium uppercase tracking-[0.7em] mb-6">Combined Valuation</p>
            <p className="text-5xl md:text-4xl font-black tracking-tighter bg-clip-text text-transparent bg-gradient-to-b from-white via-white/80 to-white/20 drop-shadow-2xl italic text-white">
              {renderBudget(itinerary.estimatedTotalCost)}
            </p>
            <div className="mt-8 flex items-center justify-center gap-3 text-[10px] font-bold text-emerald-400/60 tracking-[0.3em] uppercase">
              <CheckCircle2 className="w-3 h-3 animate-pulse" /> Sanchaara Precision Intel
            </div>
          </div>
        </footer>
      </main>
    </div>
  );
}